Map<String, String> ar = {
  "setting": "الإعدادات",
  "connect": "تواصل معنا",
  "reader": " القارئ الصوتي",
  "language": "اللغة",
  "localeEnText": "الإنجليزية",
  "localeArText": "العربية",
  "fontSize": " الخط حجم",
  "gradeColor": " درجة اللون",
  "volunteer": "المتطوع",
  "yourFamily": "للعائلة",
  "age": "العمر",
  "login": "تسجيل دخول",
  "addPost": "Add Post",
  "volunteers": "المتطوعين",
  "signUp": "   تسجيل دخول مستخدم جديد ",
  "welcomeToLilaLoginToContinue": "أهلا في LILA للمتابعة تسجيل دخول",
  "userName": "اسم المستخدم",
  "password": "كلمة السر",
  "contecttext": "تواصل معنا على ",
  "restaurantsAndCoffees": "مطاعم و مقاهي",
  "welcome": "اهلا !",
  "invalidPassword": "كلمة السر يحب ات تكون على الاقل 6 محارف",
  "isNotEmpty": "هذا الحقل لايمكن ان يكون فارغ ",
  "search": "بحث",
  "passwordHint": "أدخل كلمة المرور",
  "userNameHint": "أدخل اسم المستخدم",
  "appointmentDetails": "تفاصيل الموعد",
  "name": "اسم",
  "information": "معلومات",
  "address": "عنوان",
  "suitableforhearing": "مناسب للاعاقة السمعية",
  "lorem": "Lorem",
  "music": "الموسيقى",
  "outdoor": "الهواء الطلق",
  "elevator": " مصعد",
  "suitableforthehandicapped": "مناسب للاعاقة الحركية",
  "suitableforchildren": " مناسب للأطفال فوق ال8 سنوات ",
  "openDocumentation": "المستندات",
  "suitableforthevisually": "مناسب للاعاقة البصريه",
  "next": "التالي",
  "others": "أخرى",
  "details": "التفاصيل",
  "prescription": "وصفة",
  "transfer": "تحويل",
  "transfer1": "تحويل1",
  "notes": "ملاحظة",
  "enterNotes": "ادخل ملاحظة",
  "emptyFieldMessageError": "حقل فارغ",
  "emptyFieldMessageError2": "إدخال غير صالح",
  "enterCost": "ادخل الكلفة",
  "cost": "الكلفة",
  "status": "الحالة",
  "upcoming": "قادم",
  "onHold": "في الانتظار",
  "canceled": "ملغى",
  "finished": "منتهي",
  "inprogress": "قيد العمل",
  "waiting": "انتظار",
  "time": "الوقت",
  "enterPrescription": "ادخل الوصفة",
  "print": "طباعة",
  "save": "حفظ",
  "account": "الحساب",
  "changeLanguages": "تغير اللغة",
  "logout": "تسجيل خروج",
  "editProfile": "تعديل المعلومات",
  "request": "طلب",
  "doctorName": "اسم الطبيب",
  "diagonse": "الاعراض",
  "balance": "الرصيد",
  "attendance": "حضور",
  "signature": "توقيع",
  "certificate": "شهادة",
  "treatment": "المعالجة",
  "text": "النص",
  "calender": "التقويم",
  "balanceShouldBeMoreOrEequalThanLastBalance":
      "  الرصيد يجب ان يكون اكبر او يساوي الرصيد السابق",
  "balanceShouldBeSmallerOrEqualThanCost":
      "  الرصيد يجب ان يكون اضغر او يساوي الكلفة ",
  "paymentStatus": "  حالة الدفع",
  "viewProfile": "  عرض المعلومات",
  "leavePeriodTo": "  انتهاء تاريخ المغادرة",
  "leavePeriodFrom": "  بداية تاريخ المغادرة",
  "enterText": "  ادخل النص",
  "enterTreatment": " ادخل المعالجة",
  "enterDoctorName": "  ادخل اسم الدكتور",
  "enterRequest": "  ادخل معلومات الطلب",
  "enterDiagonse": "  أدخل معلومات الاعراض",
  "type": " النوع ",
  "viewMedicine": "  الأدوية  ",
  "moreINfo": " المزيد ",
  "phoneNumber": "رقم الهاتف",
  "email": "البريد الالكتروني",
  "takePatientPhotos": "التقاط صورة ",
  "code": " الرمز ",
  "doctors": " الاطباء ",
  "usedproducts": "المواد المستخدمة",
  "done": "النهاية",
  "prev": "السابق",
  "no": "لا",
  "yes": "نعم",
  "paid": " مدفوع ",
  "unPaid": " غير مدفوع ",
  "reload": "إعداة محاولة",
  "appointment": "الموعد",
  "profile": "المعلومات",
  "noAttachements": " لايوجد مستندات",
  "attachements": " مستندات ",
  "areYouSure": " هل أنت متاكد؟ ",
  "doYouWantToDelete": "هل انت متأكد من الحذف ؟ ",
  "english": "English",
  "arabic": "العربية",
  "german": "German",
  "plasma": "بلازما",
  "tranfer2": "تحويل2",
  "empty": "فارغة",
  "noMedicineSelected": "لم يتم اختيار اي دواء",
  "medicineList": "قائمة الادوية",
  "before": "قبل",
  "after": "بعد",
  "photolibrary": "مستعرض",
  "camera": "كاميرا",
  "personalInformation": "معلومات شخصية",
  "dateOfBirth": "تاريخ الولادة",
  "lastName": "الكنية",
  "male": "ذكر",
  "female": "أنثى",
  "other1": "غير ذلك",
  "pressTwiceToExit": "اضغط رجوع مرتين لاغلاق التطبيق",
  "nameContainText": "فقط احرف",
  "phoneValidationMessage": "  يبدأ بـ 01 أو 00 ثم من 8الى15 خانة ",
  "gender": "النوع",
  "notemail": " بريد الكتروني غير صالح",
  "createAppointment": "موعد جديد",
  "service": "الخدمة",
  "patient": "المريض",
  "color": "اللون",
  "enterPatientName": " اسم المريض",
  "newAppointment": "موعد جديد",
  "filters": "فلتر",
  "appointmentStatus": "حالة الموعد",
  "from": "من ",
  "to": "الى",
  "cancel": "الغاء",
  "actions": "تعديل",
  "patientInfo": "معلومات المريض",
  "remains": "الباقي",
  "patients": "المرضى",
  "doctor": "الطبيب",
  "previousAppointment": "المواعيد السابقة",
  "appointments": "الموعد",
  "dr": "Dr.",
  "select": "اختار",
  "ok": "موافق",
  "pleaseChooseOneServiceAtLeast": "يرجى اختيار خدمة على الاقل",
  "cannotCreateAppointmentinPast": "لا يمكن انشاء موعد في وقت سابق",
  "pleaseEnterNamelastname": "الرجاء ادخال اسم المريض بالشكل اسم كنيط",
  "patientPhotos": "صور المريض",
  "notPaid": "غير مدفوع",
  "partiallyPaid": "مدفوع جزئياً",
  "pleaseChoosePatient": "يرجى اختيار مريض",
  "doctorEmptyFieldMessageError": " اسم الطبيب يجب الا يكون فارغ",
  "requestEmptyFieldMessageError": " حقل الطلب يجب الا يكون فارغ",
  "diagonseEmptyFieldMessageError": "حقل الاعراض يجب الا يكون فارغ",
  "editPatient": "تعديل المريض",
  "notvalidDateOfBirth": "DD-MM-YYYY",
  "availableQuantities": "الكمية المتوفرة",
  "sellingCost": "سعر المبيع",
  "supplier": "المورد",
  "productName": "اسم المنتج",
  "cannotCreateAppointmentinOutWork":
      "لا يمكن إنشاء موعد خارج وقت العمل من 08:00 إلى 22:00",
  "nosgnitureChoosen": "لم يتم  اختيار توقيع ",
  "close": "اغلاق",
  "document": "المستندات",
  "laserHaarentfenernnung": "laser hair removal",
  "sizemorethanMB": "الحجم يجب ان يكون اقل من 1 ميغا",
  "sizemorethanMBB": "الحجم يجب ان يكون اقل من 5 ميغا",
  "dateShouldbeBeforNow": "تاريخ  يجب ان يكون قبل الان",
  "dateShouldbeAfterNow": "التاريخ يجب ان يكون بعد الان",
  "cropper": "اداة القص",
  "noImageSelected": "لم يتم اختيار صورة",
  "confirmed": "مؤكد",
  "phone": "الهاتف",
  "addMedicine": "أضف دواء",
  "info": "معلومات",
  "day": "يوم",
  "month": "شهر",
  "year": "سنة",
  "total": "الكل",
  "sales": "مبيعات",
  "overview": "لمحة عامة",
  "payment": "الدفع",
  "medicineNumbersMessagePrescription": "يمكن اضافة 7 أدوية فقط لكل وصفة",
  "pleaseChooseDoctor": "الرجاء اختيار دكتور",
  "patientNameFirstLast":
      "الاسم الاول و الاخير للمريض يجب ان يكونا مفصولين بفراغ",
  "appointmentDurationtooShort": "مدة الموعد قصيرة جدا",
  "clear": "الغاء",
  "orders": "الطلبات",
  "warehouse": "المخزن",
  "product": "منتج",
  "initial": "مبدئي",
  "submitted": "تم تقديمه",
  "received": "تم استلامه",
  "reset": "الغاء",
  "loginError": "خطأ في تسجيل الدخول",
  "weExperiencedAnErrorLoggingYouInWouldYouPlease":
      "حدث خطأ ما أثناء تسجيل دخولك، قم بتسجيل الدخول مرة أخرى",
  "noInternetConnection": "لايوجد اتصال بالانترنت",
  "tryAgain": "اعادة محاولة",
  "inProgress": "في تقدم",
  "paymentMethod": "طريقة الدفع",
  "chooseMethod": "اختر طريقة",
  "cash": "نقدي",
  "cards": "بطاقات",
  "enterBalance": "أدخل الرصيد",
  "enterRemains": "أدخل الباقي",
  "channel": "القناة",
  "chooseChannel": "اختر قناة",
  "chooseReason": "اختر السبب",
  "chooseCancellationReason": "اختر سبب الإلغاء",
  "youShouldLeaveACancellationReason": "يجب عليك اختيار سبب الإلغاء",
  "enterCancelReason": "أدخل سبب الإلغاء",
  "enterAddress": "أدخل عنوان",
  "uploadMoreDocuments": "تحميل المزيد من الوثائق",
  "loginText": "أدخل اسم المستخدم وكلمة المرور الخاصة بك",
  "services": "خدمات",
  "errorDateOFBirth": "يرجى التحقق من تاريخ الولادة",
  "noItemsFound": "لا يوجد نتائج",
  "invalidAddress": "اختر عنوان من القائمة",
  "editPersonalInfo": "تعديل المعلومات الشخصية",
  "position": "المنصب",
  "workingHoursPerDay": "عدد ساعات العمل في اليوم",
  "workingDaysPerWeek": "إيام العمل في الاسبوع",
  "privacyPolicy": "سياسة الخصوصية",
  "sun": "الأحد",
  "mon": "الاثنين",
  "tues": "الثلاثاء",
  "wed": "الأربعاء",
  "thu": "الخميس",
  "fri": "الجمعة",
  "sat": "السبت",
  "items": "أغراض",
  "january": "كانون الثاني",
  "february": "شباط",
  "march": "آذار",
  "april": "نيسان",
  "may": "أيار",
  "june": "حزيران",
  "july": "تموز",
  "august": "آب",
  "september": "أيلول",
  "october": "تشرين الأول",
  "november": "تشرين الثاني",
  "december": "كانون الأول",
  "otherTransfer": "غير ذلك",
  "enterMedicine": "أدخل الدواء",
  "medicine": "الدواء",
  "enterYourNotes": "أدخل ملاحظة",
  "register": "تسجيل",
  "chooseDocumentation": "اختار المستندات",
  "chooseDoctor": "اختر طبيباً",
  "enterEmailAddress": "أدخل البريد الإلكتروني",
  "enterPhoneNumber": "أدخل رقم الهاتف",
  "dayMonthYear": "اليوم-الشهر-السنة",
  "nameShouldNotContainNumbers": "لا يجب أن يحتوي الاسم على أرقام",
  "takeNewPhoto": "التقظ صورة جديدة",
  "notesAndComments": "ملاحظة",
  "images": "صور",
  "welcomeToYolo": "مرحبًا بك في Yolo",
  "chooseTheRightModulesForYou": "اختر القسم المناسب لك",
  "managementModule": "قسم الادراة",
  "eRPModule": "ERP قسم",
  "hRModule": "HR قسم",
  "getStarted": "Get Started",
  "pleaseChooseOneModule": "الرجاء اختيار وحدة واحدة",
  "switchModule": "تبديل القسم",
  "deliveries": "الواردات",
  "inventory": "المخزن",
  "vip": "مهم",
  "notVIP": "عادي",
  "sgniturenotvalid": "توقيع غير صالح",
  "birthdate": "تاريخ الميلاد",
  "home": "الصفحة الرئسية",
  "aboutMe": "حولي",
  "malls": "اسواق",
  "entertainmentAndOtherLorem": "ترفيه و أخرى لوريم",
  "connectWithUs": "اتصل بنا",
  "aboutContainsPage": "حول يحتوي على صفحة",
  "hotelsAndChalets": "الفنادق و الشاليهات",
  "you": "أنت"
};
