Map<String, String> en = {
  "localeEnText": "English",
  "localeArText": "Arabic",
  'fontSize': 'font Size',
  'gradeColor': 'Grade Color',
  "reader": " Audio Reader",
  "volunteer": "Volunteer",
  "language": "Language",
  "connect": "Connect with us",
  "setting": "Setting",
  "login": "Login",
  "addPost": "Add Post",
  "signUp": "Sign Up",
  "age": "Age",
  "contecttext": "Contact Us on ",
  "volunteers": "Volunteers",
  "suitableforthevisually": "Suitable for the visually impaired",
  "suitableforhearing": " Suitable for hearing impaired ",
  "suitableforchildren": "Suitable for children >8y",
  "welcomeToLilaLoginToContinue": "Welcome To LILA Login To Continue",
  "loginText": "Enter your username and password",
  "userName": "Username",
  "password": "Password",
  "outdoor": "Outdoor",
  "information": "Information",
  "elevator": "Elevator",
  "music": "Music",
  "suitableforthehandicapped": "Suitable for the handicapped",
  "welcome": "Welcome",
  "invalidPassword": "Must be at least 6 characters long",
  "isNotEmpty": "This Field can't be empty ",
  "passwordHint": "Enter Password",
  "userNameHint": "Enter Username",
  "appointmentDetails": "Appointment Details",
  "wizardFirstPageTitle": "Privatpraxis Krstin Madri",
  "wizardFirstPageUpperPartFirst": "Dear Patient,",
  "wizardFirstPageUpperPartSeconde":
      "The protection of your data is important to us. Due to the treatment relationship with you, we are allowed to collect and process your data. In order to transfer your data in connection with your treatment to other service providers (e.g. other doctors, hospitals, laboratories) (e.g. by means of a doctor's letter) or to obtain it from other service providers, your consent is required at some points. Without this, we cannot adequately treat and inform the service providers. Otherwise we ask you to transmit the data to the service provider yourself or to obtain it from them. Your consent is also required for the information and exchange of your data to and with your relatives. We would like to point out that a rack connection to your clinical picture is possible on the basis of the documents mentioned.",
  "wizardFirstPageCheckBoxTitle": "You can give us your consent below:",
  "wizardFirstPageCheckBox":
      "With my signature, I agree that my personal data (e.g. master data, insurance data and health data) may be exchanged with the following service providers for the purpose of continuous treatment and gapless documentation by Praxis Madri.",
  "wizardFirstPageName": "Name first Name",
  "name": "Name",
  "address": "Address",
  "lorem": "Lorem",
  "unterschrift": "signature",
  "ortDatum": "Place and date",
  "openDocumentation": "Open Documentation",
  "praxisLiLa": "Praxis Krstin Madrí",
  "aufklarungsbogenAsthetik": "Aesthetics information sheet",
  "firstParagraph":
      "Dear patient, this information sheet is used to prepare for the informational discussion. Please read it carefully before the interview and carefully fill out the questionnaire.",
  "treatmentoptions": "The treatment options: (Please select)",
  "dasFadenlifting": "The thread lifting",
  "dasFadenliftingDescription":
      "The principle of thread lifting consists in tightening tissue and lifting the sunken soft tissue again. The thread lifting can reduce strong wrinkles and lowered fat tissue can be raised again. The threads should bring about a collagen synthesis that stabilizes the tightening and develop a permanent holding effect due to their barbed surface texture.",
  "botulinumtoxin": "Botulinum toxin A",
  "botulinumtoxinDescription":
      "These agents inhibit the transmission of nerve impulses that trigger the drawing together of the muscles and thus contribute to the formation of mimic wrinkles. Depending on the dosage, the movement is inhibited or only severely restricted. However, since only a part of the facial muscles is affected, there is no mask-like face. The muscle tension in the treated areas subsides, which leads to significant relaxation of the skin and a reduction in wrinkles in the following days. The other facial muscles are not affected. Botulinum toxin A are particularly suitable for avoiding forehead lines, frown lines and crow's lips. In the case of certain pre-existing conditions (e.g. congenital muscle weakness), the injection cannot be given.",
  "hyaluronsaure": "Hyaluronic acid",
  "hyaluronsaureDescription":
      "The tissue filler must be injected exactly into the skin layer in which tissue loss has led to the formation of wrinkles. It may be necessary to inject directly into the individual skin layers (interdermal) or under the skin (subcutaneous). In some cases, a local anesthetic is used to avoid pain, but in most cases it can be dispensed with. Some tissue fillers are massaged into the skin after the injection in order to achieve an even result.",
  "pRP": "PRP",
  "prpDescription":
      "If platelet-rich plasma is used for tissue injection, some blood will first be taken from your arm vein. The blood is then further processed using a special procedure to separate the red blood cells (centrifugation). The thick blood plasma that remains is used directly for injection.",
  "kostenubernahme": "Assumption of costs:",
  "kostenubernahmeDescription":
      "The health insurance company does not cover the costs of these treatments and any complications that may require treatment.",
  "risikenMogliche": "Risks and possible complications:",
  "risikenMoglicheDescription":
      "Despite all the care, it can lead to -u.U. There are also life-threatening complications that require further treatment / operations. Pre-existing illnesses and individual peculiarities can significantly influence the frequency of complications.",
  "risikenFirst":
      "Immediately after the injection, a small bruise may form at the injection site, which will subside after a few days, rarely after 2-3 weeks. Discoloration of the skin caused by bruises can in exceptional cases be visible for months.",
  "risikenSecondnd":
      "If the substance is distributed in the tissue, the upper eyelid or brow may temporarily hang. When treating crow's feet, distribution of the substance around the eyes may cause temporary visual disturbances. These symptoms disappear again within a few weeks. (only for botulinum toxin).",
  "risikenThirdrd":
      "Nerve injuries: an injury to the facial nerve in the lower facial area can lead to paralysis of the affected half of the face, as well as functional impairment of nerves (paresthesia, facial disorders). Most of them are temporary.",
  "risikenForth":
      "Botulinum toxin preparations contain small amounts of human blood protein®. The risk of getting yourself through the administration of the",
  "wizardRegisterFirstPageTitle": "Private practice Krstin Madri",
  "wizardRegisterFirstPageUpperPartFirst": "Dear Patient,",
  "wizardRegisterFirstPageUpperPartSeconde":
      "The protection of your data is important to us. Due to the treatment relationship with you, we are allowed to collect and process your data. In order to transfer your data in connection with your treatment to other service providers (e.g. other doctors, hospitals, laboratories) (e.g. by means of a doctor's letter) or to obtain it from other service providers, your consent is required at some points. Without this, we cannot adequately treat and inform the service providers. Otherwise we ask you to transmit the data to the service provider yourself or to obtain it from them. Your consent is also required for the information and exchange of your data to and with your relatives. We would like to point out that a rack connection to your clinical picture is possible on the basis of the documents mentioned.",
  "wizardRegisterFirstPageCheckBoxTitle": "You can give us your consent below:",
  "wizardRegisterPageCheckBox":
      "With my signature, I agree that my personal data (e.g. master data, insurance data and health data) may be exchanged with the following service providers for the purpose of continuous treatment and gapless documentation by Praxis Madri.",
  "acceptanceConditionsMessage":
      "please accept the Terms and Conditions to continue",
  "next": "Next",
  "thiemeCompliance": "Thieme Compliance",
  "khnikeindruck": "khnikeruck / Stempet",
  "patientenditen": "Patient returns / Autkieber",
  "sehrGeehrtePatientin": "Dear Patient",
  "sieMochtenEine":
      "You would like to have an operative eyelid surgery performed. This information sheet is used to prepare for the informative discussion. Please read it carefully before the interview and fill out the questionnaire conscientiously.",
  "wannIstDerEingriffSinnvoll": "When does the procedure make sense?",
  "wannIstDerEingriffSinnvollDescription":
      "The elasticity of the eyelid skin and eyelid muscles can decrease in the course of your life, in younger people also due to their condition, and the fatty tissue of the eye jar can bulge out. This leads to typical alversal changes such as wrinkles. Drooping eyelids or | so-called. Under-eye bags. \n The operation can partially remove excess skin to eliminate wrinkles and sagging, as well as the slack tissue (e.g. muscle) lying thereunder, or tighten it with appropriate seams, so-called eye bags can be effectively treated by reducing or relocating the fatty tissue will. \n The upper eyelids are most often affected by the relaxation. but often also the lower eyelids. Even if the original elasticity of the skin cannot be completely restored, the operation usually results in a significant rejuvenation of your appearance. In addition to slackening of the eyelid skin, other phenomena can also impair the appearance and function of the eyelids, such as 2.B. The droop ng of the eyebrows, excessive slackening of the tissues of the cheeks and temples, changes in the lifting muscles of the eyelids or other functional disorders of nerves, muscles and blood vessels. This must be determined precisely by your doctor before the operation. The last page of this information sheet states which individual measures are planned for you, \n",
  "kostenubernahmeDocSeconde":
      "This intervention is made for aesthetic reasons. Considered, the health insurers usually do not cover the costs of this treatment and any complications that may require treatment. Therefore, these questions should be clarified in advance with the health insurance company and the doctor. In addition, the conclusion of a follow-up cost insurance should then be considered.",
  "wieWirdOperiert": "How do you operate?",
  "wieWirdOperiertDescription":
      "The procedure can be performed under local or general anesthesia. The surgeon or anesthetist will explain the specific risks of general anesthesia to you separately. Before the surgical tightening of the eyelids, your doctor will make an exact drawing on the skin of the eyelids, which will mark the excess skin and give him important clues for the removal of skin, muscles and fatty tissue as well as the final suture during the operation. The operation cannot be performed without leaving scars. The incision runs in the natural folds of the skin of the upper eyelid and, if necessary, below the eyelashes of the lower eyelid, laugh lines and crows (some also require 5-10 mm long cuts on the outer corner of the eye, which are placed in natural skin lines so that the scars are later as inconspicuous as possible, The natural reddening of a fresh seam scar disappears after 2-3 weeks, but in individual cases it can last for several months",
  "sampleInformatoinsheetForTreatment":
      "SAMPLE - INFORMATION SHEET FOR TREATMENT",
  "dataToBeTreated": "Data to be treated",
  "hairRemoval": "Laser hair removal",
  "legsLowerOrThigh": "Legs: thighs / lower legs",
  "armsArmpitsShouldersForearms": "Arms: armpits / shoulders / forearms",
  "brustRackenBBikiniZone": "Chest / back / bikini zone",
  "face": "face",
  "hypertrichoseHirsutismus": "Hypertrichosis / hirsutism",
  "others": "other",
  "institutePractice": "Institute / practice.",
  "dearCustomerPatient": "Dear customer / patient",
  "dearCustomerPatientDescription":
      "You would like to have annoying hair on the face or body permanently removed with the laser. It is the responsibility of your bohandler to inform you about the upcoming treatment. The method, risks, side effects and chances of success of the laser treatment are discussed. Please read this information carefully and discuss any possible carry-backs with your practitioner. \n",
  "permanentHairRemovalWithTheLaser": "Permanent hair removal with the laser",
  "howDoesLaserHairRemovalTreatmentWork":
      "How does laser hair removal treatment work?",
  "howDoesLaserHairRemovalTreatmentWorkDescription":
      "During the laser treatment for hair removal, an intense laser beam penetrates the skin with high energy and wicks specifically into the hair root. This is where the pigment melanin sits, which absorbs the energy of the laser. The hair root is heated \n by the laser energy and reliably destroyed, after a while the hair will fall out. The skin surface and the surrounding tissue are spared, since the melanin concentration in the hair roots is significantly higher than in the rest of the skin, even with darker skin types, and the energy only acts in the melanin. Both fine and thick, lighter and dark, superficial or deep-lying hair can be successfully removed with the laser treatment. \n",
  "howIsLaserHairRemovalPerformed": "How is laser hair removal performed?",
  "howIsLaserHairRemovalPerformedDescription":
      "The laser treatment is carried out on an outpatient basis in your practice / institute. If necessary, a trial treatment is carried out on a small area before the actual treatment. Local anesthesia or anesthesia are not necessary. During the treatment, the skin surface is cooled; if necessary, it can also be pre-cooled for desensitization.",
  "howDoesLaserHairRemovalFeelLike": "How does laser hair removal feel like?",
  "howDoesLaserHairRemovalFeelLikeDescription":
      "Laser hair removal causes a slight sensation of warmth and can cause a slight stinging in the skin of sensitive skin. Skin cooling reduces these side effects considerably and increases comfort.",
  "whenShouldLaserHairRemovalTreatmentBeAvoided":
      "When should laser hair removal treatment be avoided?",
  "additionalInformationPractitioner":
      "Additional information on the treatment of the practitioner",
  "safetyHistoryWhatYourPractitionerShouldKnow":
      "Safety history - what your practitioner should know:",
  "areYouTakingAnyMdicationThatMakesYouMoreSensitiveToLight":
      "Are you taking medication that increases sensitivity to light?",
  "areYouCurrentlyTakingAnyOtherMedication":
      " Are you currently taking any other medication?",
  "areYouKnownToHaveAbnormalScarring":
      "Are you known to have abnormal scarring, e.g. after laser treatment?",
  "areYouProneToHerpes": "Are You Prone To Herpes?",
  "areYouProneToHyperOrHypopigmentation":
      "Are you prone to hyper- or hypopigmentation?",
  "doYouHaveCardiovascularDisease":
      "Do you have a cardiovascular disease, e.g. Herziehler or high blood pressure?",
  "areYouBreastfeeding": "Are you pregnant or are you breastfeeding?",
  "otherLauren": "Other lauren de Batanderin / the agile to araâraer)",
  "sonstigesLaurenDeBatanderinDenBehenderZuAraaraer":
      "‘Other lauren de Batanderin / the agile to araâraer)",
  "doesTheHealthInsuranceCompanyCoverTheCostsOfLaserHairRemovalTreatment":
      "Übernimmt die Krankenkasse die Kosten der Laserbehandlung zur Haarentfernung?",
  "asARuleTheHealthInsuranceDoesNotCoverTheCostsForLaserHairRemovalThereAreExceptionalCases":
      "As a rule, the health insurance does not cover the costs for laser hair removal, but there are exceptional cases your practitioner will give you more detailed advice.",
  "thisIsANonBindingSampleForPatient":
      "This is a non-binding sample for patient  customer education discussions. Alma Lasers GmbH assumes no liability for the correctness and \n completeness of the information. This document must be adapted by the practitioner to the conversation with the individual \n to be treated. This sample is not legally binding and does not replace an individual consultation between the practitioner and the person to be treated> \n Sample explanation laser hair removal Rev2 17_06_2019",
  "clinicPractice": "Clinic / practice",
  "patientNameAndAddress": "Patient name and address",
  "dearPatient": "Dear Patient",
  "thisInformationSheetIsUsedToPrepareForTheInformationInterview":
      "This information sheet is used to prepare for the information interview. Please read it carefully before the interview and fill out the questionnaire carefully.",
  "liposuction": "Liposuction",
  "liposuctionDescription":
      "With the surgical procedure of liposuction (liposuction), accumulations of fat under the skin can be permanently removed from almost any part of the body. However, liposuction is not a means of weight loss or a method of treating obesity. It is only used for fat distribution disorders and to correct problem areas that cannot be influenced by diet and exercise. Under certain conditions, liposuction is also possible on the face and neck. \n The doctor will note the places you will have liposuction on on the last page of this information sheet.",
  "assumptionOfCosts": "Assumption of costs",
  "asRuleTheHealthInsuranceCompanyDoesNotCoverTheCostsOfTheTreatment":
      "As a rule, the health insurance company does not cover the costs of the treatment and any complications that may require treatment. Therefore, the question of costs should be clarified in advance with your doctor / your health insurance company,",
  "howIsTheProcedurePerformed": "How is the procedure performed?",
  "dependingOnTheMethodAndExtentOfTheProcedure":
      "Depending on the method and extent of the procedure, liposuction is performed under local anesthesia (tumescent local anesthesia, usually in combination with the administration of a sedative) or under general anesthesia (general anesthesia). to be clarified separately.",
  "theMethodsOfLiposuction": "The methods of liposuction",
  "theMostCommonProcedureIsTheTumescentTechniqueCarriedOut":
      "Am häufigsten wird der Eingriff mit der Tumeszenztechnik durchgeführt, zu der wir auch in Ihrem Fall raten. Es handelt sich hierbei um die Verwendung von Medikamenten (z.B.Betäubungsmitteln) au&erhalb ihres Zulassungsbereichs (Off-Label-Use). Dies ist zulässig, sofern Sie der Verwendung nach eingehender Aufklärung zustimmen. Über mögliche Nebenwirkungen der dabei eingesetzten Medikamente wird Sie Ihr Arzt anhand des Beipackzettels informieren.\nUm die Fettzellen zunächst zu lockern und die Blutungsnei-\ngung zu verringern, wird bei dieser Technik vor der Fettabsaugung eine gröBere Menge Flüssigkeit (Kochsalzlösung)",
  "footerForthDocPage":
      "Dokumentierte Patientenaufklärung » Herausgeber: Prof. K. Ulsenheimer (Medizinrecht) - Gründungshrsg.: Prof, W. Weißauer  \nFachgebietshrsg.: Prof. Dr. W. Gubisch - Autoren: Dr. M. Bromba, Prof. Dr. W, Gubisch - © 2019 by Thieme Compliance GmbH, 91058 \nErlangen - Vervielfältigungen jeglicher Art, auch Fotokopieren, verboten.\nBestell-Adresse: Thieme Compliance GmbH, Am Weichselgarten 30a, 91058 Erlangen, Tel, +49 (09131 93406-40, Bestell-Fax 93406-70 - www.thieme-compliance.de",
  "footerForthDocPage2": " Red. 03/2019\nPDF 04/2019\nBestell-Nr. DEO16013",
  "patientData": "Patient data",
  "skinRejuvenationFacial": "Skin rejuvenation facial",
  "skinRejuvenationOnTheNeckDecollete":
      "Skin rejuvenation on the neck / décolleté",
  "wrinkleTreatmentPeripheralPeriodical":
      "Wrinkle treatment perioral / periorbital",
  "scarTreatment": "Scar treatment",
  "treatmentOfUnevenPigmentation": "Behandlung ungleichmäßiger Pigmentierungen",
  "dearPatientSeconde": "Dear patient",
  "dearPatientSecondeDescriptionDoc4":
      "You would like to have disruptive changes in the skin treated with the fractionated laser. It is your doctor's duty to tell you about the upcoming treatment. It discusses the method, risks, side effects and \n  errelment prospects of the laser treatment. Please read this information carefully and discuss any questions you may have with your doctor",
  "fractionalLaserTreatment": "Fractional \n laser treatment",
  "fractionalLaserTreatmentBtn": "Fractional  laser treatment",
  "fractionalLaserTreatmentOneLine":
      "How does fractional laser treatment work?",
  "howDoesFractionalLaserTreatmentWork":
      "How does fractional laser treatment work?",
  "howDoesFractionalLaserTreatmentWorkDescription":
      "The energy of the fractional laser is absorbed in the tissue water. The water evaporates, removing hundreds of microscopic areas of the skin's surface. These tiny areas are surrounded by untreated tissue. As a result, they heal very quickly and fresh, smooth skin is formed. With each treatment, part of the skin surface is renewed. At the same time, the heat of the fractionated laser stimulates the formation of new firming collagen in the connective tissue deep within the skin.",
  "howIsFractionalLaserTreatmentPerformed":
      "How is fractional laser treatment performed?",
  "howIsFractionalLaserTreatmentPerformedDescription":
      "The fractional laser treatment is carried out on an outpatient basis in the above-mentioned practice / clinic. The treatment can be carried out under local anesthesia. Anesthesia is not necessary as the skin is cooled during the laser treatment in order to reduce the sensitivity to pain. If necessary, a test treatment is carried out first.",
  "howDoesFractionalLaserTreatmentFeel":
      "How does fractional laser treatment feel?",
  "howDoesFractionalLaserTreatmentFeelDescription":
      "Fractional laser treatment can cause a slight burning or stinging sensation in the skin. Some patients describe this feeling as being like clicking a rubber band on the skin. The skin cooling and, if necessary, a local anesthetic, e.g. with a cream, reduce these unpleasant side effects and increase your comfort during the treatment. After the treatment, the skin may feel like a light sunburn for a few hours.",
  "whenShouldFractionalLaserTreatmentBeAvoided":
      "When should fractional laser treatment be avoided?",
  "whenShouldFractionalLaserTreatmentBeAvoidedDescription":
      "Sun and solar tanned skin are not suitable for the frationed laser treatment, patients must not be sensitive to light and should not have a tendency to develop herpes. Further contraindications are dermatoses with Koebner phenomenon, muscular rhythms, previous illnesses with keloid formation, medication with isotretinoin, collagen defects, cutaneous infection of the areas to be treated, also acne, skin type IV and higher (Fitzpatrick scale), tendency to hypo- / hyperpigmentation .",
  "safetyHistoryWhatYourDoctorShouldKnow":
      "Safety History - What Your Doctor Should Know:",
  "areYouTakingMedicationThatIncreasesTheSensitivityToLight":
      "Are you taking medication that increases the sensitivity to light?",
  "doYouHaveAnyKnownHypersensitivityToLocalAnesthetics":
      "Do you have any known hypersensitivity to local anesthetics?",
  "areYouAnalForHerpes": "Are You Anal For Herpes?",
  "areYouProneToScarringOrLoosing": "Are you prone to scarring or loosing?",
  "ifYouHaveACardiovascularDiseaseHeartDefectOrHighBloodPressure":
      "If you have a cardiovascular disease. e.g. heart defect or high blood pressure?",
  "areYouPregnantOrAreYouInThreesome":
      "Are you pregnant or are you in threesome?",
  "doesTheHealthInsuranceCompanyCoverTheCostsOfLaserHairRemovalTreatmentDoc3":
      "Does the health insurance company cover the costs of laser hair removal treatment?",
  "doesTheHealthInsuranceCompanyCoverTheCostsOfLaserHairRemovalTreatmentDoc3Descritpion":
      "As a rule, the health insurance does not cover the costs of laser hair removal, but there are exceptions, all \n your practitioner will give you more detailed advice on this.",
  "details": "Details",
  "prescription": "Prescription",
  "transfer": "Transfer",
  "transfer1": "Transfer1",
  "notes": "Notes",
  "enterNotes": "Enter Notes",
  "emptyFieldMessageError": "Field is empty",
  "emptyFieldMessageError2": "not valid input",
  "enterCost": "Enter Costs",
  "cost": "Cost",
  "status": "Status",
  "upcoming": "Upcoming",
  "onHold": "OnHold",
  "canceled": "Canceled",
  "finished": "Finished",
  "inprogress": "Inprogress",
  "waiting": "Waiting",
  "time": "Time",
  "enterPrescription": "Enter Prescription",
  "print": "PRINT",
  "save": "SAVE",
  "account": "Account",
  "changeLanguages": "Change Languages",
  "logout": "Logout",
  "editProfile": "Edit Profile",
  "request": "Request",
  "doctorName": "Doctor Name",
  "diagonse": "Diagonse",
  "balance": "Balance",
  "attendance": "Attendance",
  "signature": "Signature",
  "certificate": "Certificate",
  "treatment": "Treatment",
  "text": "Text",
  "calender": "Calendar",
  "balanceShouldBeMoreOrEequalThanLastBalance":
      "balance should be more or equal  than last balance",
  "balanceShouldBeSmallerOrEqualThanCost":
      "balance should be smaller or equal  than cost ",
  "paymentStatus": "Payment Status ",
  "viewProfile": "View Profile",
  "leavePeriodTo": "leave Period To",
  "leavePeriodFrom": "leave Period From",
  "enterText": "  Enter Text",
  "enterTreatment": "  Enter Treatment",
  "enterDoctorName": "  Enter Doctor Name",
  "enterRequest": "  Enter Request",
  "enterDiagonse": "  Enter Diagonse",
  "type": "Type",
  "viewMedicine": "View Medicine",
  "moreINfo": "More Info",
  "phoneNumber": "Phone Number",
  "email": "Email",
  "takePatientPhotos": "Take Patient Photos",
  "code": "Code",
  "doctors": "Doctors",
  "usedproducts": "Used products",
  "done": "Done",
  "prev": "Prev",
  "no": "No",
  "yes": "Yes",
  "paid": "Paid",
  "unPaid": "Unpaid",
  "reload": "Reload",
  "appointment": "Appointment",
  "profile": "Profile",
  "noAttachements": "no Attachements",
  "attachements": "Attachements",
  "areYouSure": "Are you sure?",
  "doYouWantToDelete": "Do you want to Delete this Doc",
  "english": "English",
  "arabic": "العربية",
  "german": "German",
  "plasma": "Plasma",
  "tranfer2": "Transfer2",
  "empty": "empty",
  "noMedicineSelected": "no Medicine Selected",
  "medicineList": "medicine List",
  "before": "Before",
  "after": "After",
  "photolibrary": "photo Library",
  "camera": "Camera",
  "personalInformation": "Personal Information",
  "dateOfBirth": "Date Of Birth",
  "birthdate": "Birthdate",
  "lastName": "Last Name",
  "male": "male",
  "female": "female",
  "other1": "other",
  "pressTwiceToExit": "Press Twice To Exit",
  "nameContainText": "text only",
  "phoneValidationMessage":
      "start with either 0 or 00 and then a numbers between 8 and 15",
  "gender": "Gender",
  "notemail": "not valid email",
  "createAppointment": "Create Appointment ",
  "service": "Service",
  "patient": "Patient",
  "color": "color",
  "enterPatientName": "Enter Patient Name",
  "newAppointment": "New Appointment",
  "filters": "Filters",
  "appointmentStatus": "Appointment Status",
  "from": "From",
  "to": "to",
  "cancel": "Cancel",
  "actions": "Actions",
  "patientInfo": "Patient Info",
  "remains": "Remains",
  "patients": "Patients",
  "doctor": "Doctor",
  "previousAppointment": "Previous Appointments",
  "appointments": "Appointments",
  "dr": "Dr.",
  "select": "select",
  "ok": "ok",
  "pleaseChooseOneServiceAtLeast": "please choose one service at least",
  "cannotCreateAppointmentinPast": "Can't Create Appointment in Past",
  "pleaseEnterNamelastname": "Please enter 'Name lastname'",
  "patientPhotos": "Patient Photos",
  "notPaid": "not Paid",
  "partiallyPaid": "partially Paid",
  "pleaseChoosePatient": "please Choose Patient",
  "doctorEmptyFieldMessageError": " Doctor Name should not be empty",
  "requestEmptyFieldMessageError": " Request should not be empty",
  "diagonseEmptyFieldMessageError": " Diagonse should not be empty",
  "editPatient": "Edit Patient",
  "notvalidDateOfBirth": "DD-MM-YYYY",
  "availableQuantities": "Available Quantities",
  "sellingCost": "Selling Cost",
  "supplier": "supplier",
  "productName": "Product Name",
  "cannotCreateAppointmentinOutWork":
      "can not use  Out Work Time 08:00 to 22:00",
  "nosgnitureChoosen": "no sgniture choosen ",
  "close": "close",
  "document": "Documents",
  "laserHaarentfenernnung": "laser hair removal",
  "sizemorethanMB": "Size should be less than 1 MB",
  "sizemorethanMBB": "Size should be less than 5 MB",
  "dateOfBirthShouldbeBedorNow": "Date should be before Now",
  "dateShouldbeAfterNow": "Date should be after Now",
  "cropper": "Cropper",
  "noImageSelected": "No image selected",
  "phone": "Phone",
  "confirmed": "Confirmed",
  "addMedicine": "Add Medicine",
  "info": "Info",
  "day": "Day",
  "month": "Month",
  "year": "Year",
  "total": "total",
  "sales": "Sales",
  "overview": "Overview",
  "payment": "payment",
  "medicineNumbersMessagePrescription":
      "only 7 medicine can be added to one  prescription",
  "pleaseChooseDoctor": "please choose Doctor",
  "patientNameFirstLast":
      "patient first and last name must be separated by space",
  "appointmentDurationtooShort": "Appointment Duration too Short",
  "clear": "Clear",
  "orders": "Orders",
  "warehouse": "Warehouse",
  "product": "product",
  "initial": "Initial",
  "submitted": "Submitted",
  "received": "Received",
  "reset": "RESET",
  "inProgress": "In Progress",
  "loginError": "Login Error",
  "weExperiencedAnErrorLoggingYouInWouldYouPlease":
      "We Experienced an Error Logging You in, would you please log in again?",
  "noInternetConnection": "No Internet Connection",
  "tryAgain": "Try Again",
  "paymentMethod": "Payment Method",
  "chooseMethod": "Choose method",
  "cash": "Cash",
  "cards": "Cards",
  "enterBalance": "Enter Balance",
  "enterRemains": "Enter remains",
  "channel": "Channel",
  "chooseChannel": "Choose Channel",
  "chooseReason": "Choose Reason",
  "chooseCancellationReason": "Choose Cancellation reason",
  "youShouldLeaveACancellationReason":
      "You should choose a cancellation reason",
  "enterCancelReason": "Enter Cancel Reason",
  "enterAddress": "Enter address",
  "uploadMoreDocuments": "Upload more documents",
  "yolo": "yolo",
  "january": "January",
  "february": "February",
  "march": "March",
  "april": "April",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "October",
  "november": "November",
  "december": "December",
  "errorDateOFBirth": "not valid date of birth",
  "otherTransfer": "Other",
  "enterMedicine": "Enter medicine",
  "medicine": "Medicine",
  "register": "Register",
  "chooseDocumentation": "Choose Documentation",
  "services": "Services",
  "noItemsFound": "No Items Found",
  "invalidAddress": "Choose Address from the list",
  "editPersonalInfo": "Edit Personal Info",
  "position": "Position",
  "workingHoursPerDay": "Working Hours Per Day",
  "workingDaysPerWeek": "Working Days Per Week",
  "privacyPolicy": "Privacy Policy",
  "sun": "Sun",
  "mon": "Mon",
  "tues": "Tues",
  "wed": "Wed",
  "thu": "Thu",
  "fri": "Fri",
  "sat": "Sat",
  "warehouses": "Warehouses",
  "items": "Items",
  "quantity": "Quantity",
  "notesComments": "Notes Comments",
  "chooseDoctor": "Choose Doctor",
  "enterEmailAddress": "Enter Email Address",
  "enterPhoneNumber": "Enter Phone Number",
  "dayMonthYear": "day - month - year",
  "nameShouldNotContainNumbers": "Name should not contain numbers",
  "takeNewPhoto": "take new photo",
  "notesAndComments": "notes and comments",
  "images": "Images",
  "sgniturenotvalid": "signature not valid",
  "To": "To",
  "enterYourNotes": "Enter your notes",
  "welcomeToYolo": "Welcome to Yolo",
  "chooseTheRightModulesForYou": "Choose the right modules for you",
  "managementModule": "Management Module",
  "eRPModule": "ERP Module",
  "hRModule": "HR Module",
  "getStarted": "Get Started",
  "pleaseChooseOneModule": "Please Choose One Module",
  "switchModule": "Switch Module",
  "deliveries": "Deliveries",
  "inventory": "Inventory",
  "vip": "VIP",
  "notVIP": "normal",
  "chooseImage": "choose image",
  "upload": "upload",
  "search": "Search",
  "loginTime": "login Time",
  "chooseTypeOfLeave": "choose Type Of Leave",
  "activeNow": "active Now",
  "loggedOut": "logged Out",
  "leave": "leave",
  "breeak": "break",
  "restaurantsAndCoffees": "Restaurants And Coffees",
  "yourFamily": "Your Family",
  "noImages": "no Images",
  "employeeList": "employee List",
  "checkOut": "checkOut",
  "checkin": "checkin",
  "employeeCheckIn": "employee Check In",
  "enterEntryPin": "enter Entry Pin",
  "pin": "pin",
  "letsGo": "Let's Go",
  "forgetpassword": "Forget Password",
  "donotHaveAnAccount": "do not Have An Account",
  "home": "Home",
  "aboutMe": "aboutMe",
  "malls": "Malls",
  "entertainmentAndOtherLorem": "Entertainment And Other Lorem",
  "ConnectWithUs": "Connect With Us",
  "aboutContainsPage": "About Contains Page",
  " Restaurants and Coffees": "Restaurants and Coffees",
  "hotelsAndChalets": "Hotels and Chalets",
  "you": "You"
};
