import 'package:get/get.dart';

class TKeys {
  String fontSize = "Font Size".tr;
  String gradeColor = "Grade Color".tr;
  String localeEnText = 'localeEnText'.tr;
  String localeArText = 'localeArText'.tr;
  String connect = "connect".tr;
  String reader = 'reader'.tr;
  String setting = 'setting'.tr;
  String contecttext = 'contecttext'.tr;
  String login = 'login'.tr;
  String age = "age".tr;
  String password = 'password'.tr;
  String search = 'search'.tr;
  String home = 'home'.tr;
  String signUp = 'signUp'.tr;
  String malls = 'malls'.tr;
  String entertainmentAndOtherLorem = 'entertainmentAndOtherLorem'.tr;
  String connectWithUs = 'connectWithUs'.tr;
  String aboutContainsPage = 'aboutContainsPage'.tr;
  String restaurantsAndCoffees = 'restaurantsAndCoffees'.tr;
  String hotelsAndChalets = 'hotelsAndChalets'.tr;
  String next = 'next'.tr;
  String name = 'name'.tr;
  String type = 'type'.tr;
  String gender = 'gender'.tr;
  String welcome = 'welcome'.tr;
  String userName = 'userName'.tr;
  String details = 'details'.tr;
  String account = 'account'.tr;
  String phoneNumber = 'phoneNumber'.tr;
  String email = 'email'.tr;
  String no = 'no'.tr;
  String passwordHint = 'passwordHint'.tr;
  String userNameHint = 'userNameHint'.tr;
  String isNotEmpty = 'isNotEmpty'.tr;
  String yes = 'yes'.tr;
  String english = 'english'.tr;
  String arabic = 'arabic'.tr;
  String male = 'male'.tr;
  String female = 'female'.tr;
  String yourFamily = 'yourFamily'.tr;
  String color = 'color'.tr;
  String ok = 'ok'.tr;
  String close = 'close'.tr;
  String info = 'info'.tr;
  String loginError = 'loginError'.tr;
  String enterEmailAddress = 'enterEmailAddress'.tr;
  String dateOfBirth = 'dateOfBirth'.tr;
  String changeLanguages = 'changeLanguages'.tr;
  String save = 'save'.tr;
  String invalidPassword = 'invalidPassword'.tr;
  String you = 'you'.tr;
  String volunteers = 'volunteers'.tr;
  String volunteer = 'volunteer'.tr;
  String language = 'language'.tr;
  String suitableforchildren = 'suitableforchildren'.tr;
  String suitableforhearing = 'suitableforhearing'.tr;
  String suitableforthevisually = 'suitableforthevisually'.tr;
  String suitableforthehandicapped = 'suitableforthehandicapped'.tr;
  String music = 'music'.tr;
  String outdoor = 'outdoor'.tr;
  String elevator = 'elevator'.tr;
  String information = 'information'.tr;
}

//TKeys.hello
