List<String> horelsImages = [
  "assets/imagePleases/hotels/Assila_Hotel-Exterior.jpeg",
  "assets/imagePleases/hotels/فندق الدار البيضاء.jpeg",
  "assets/imagePleases/hotels/فندق ميراج.jpeg",
  "assets/imagePleases/hotels/فندق كراون بلازا.jpeg",
  "assets/imagePleases/hotels/فندق تاج جدة.jpeg",
];

List<String> marketsImages = [
  "assets/imagePleases/markets/رد سي مول.jpeg",
  "assets/imagePleases/markets/مجمع العرب.jpeg",
  "assets/imagePleases/markets/عزيز مول.jpeg",
  "assets/imagePleases/markets/روايع المكتبات.jpeg",
  "assets/imagePleases/markets/موفي سينما.jpeg",
  "assets/imagePleases/markets/بيت ورد.jpg",
  "assets/imagePleases/markets/الياسيمن مول.jpeg",
  "assets/imagePleases/markets/هيفاء مول.jpeg",
  "assets/imagePleases/markets/الاندلس مول.jpeg",
  "assets/imagePleases/markets/السلام مول.jpeg",
  "assets/imagePleases/markets/الجامعه بلازا.jpeg",
];

List<String> resturantImages = [
  "assets/imagePleases/resturant/اغافي.jpeg",
  "assets/imagePleases/resturant/بابايا.jpeg",
  "assets/imagePleases/resturant/اروما.jpeg",
  "assets/imagePleases/resturant/بلو اوشن.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/اكس تريب.jpeg",
  "assets/imagePleases/resturant/ثلث.jpg",
  "assets/imagePleases/resturant/هايد اوت.jpeg",
  "assets/imagePleases/resturant/كافين لاب.jpg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/انجلينا.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/ميز.jpeg",
  "assets/imagePleases/resturant/خيال.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/لوكنشير.jpeg",
  "assets/imagePleases/resturant/تميس.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/ستيتة.jpeg",
  "assets/imagePleases/resturant/نوفل.jpeg",
  "assets/imagePleases/resturant/مكان زمان.jpeg",
  "assets/imagePleases/resturant/سراوند.jpeg",
  "assets/imagePleases/resturant/جامبا.jpeg",
  "assets/imagePleases/resturant/كتشب.jpeg",
  "assets/imagePleases/resturant/القلزم.jpeg",
  "assets/imagePleases/resturant/ازور القهوة المختصة.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/كوينز.jpeg",
  "assets/imagePleases/resturant/كابانا.jpeg",
];

List<String> parkImages = [
  "assets/imagePleases/parks/الشلال.jpg",
  "assets/imagePleases/parks/الارض السعيده.jpg",
  "assets/imagePleases/parks/الشلال.jpg",
  "assets/imagePleases/parks/الواجهة .jpeg",
  "assets/imagePleases/parks/موفنبيك.jpeg",
  "assets/imagePleases/parks/ملاهي سماش.jpeg",
  "assets/imagePleases/parks/متحف.jpg",
  "assets/imagePleases/parks/حديقة الفيحا.jpeg",
  "assets/imagePleases/parks/مدينة الملك عبدالله.jpeg",
  "assets/imagePleases/parks/انجليز.jpeg",
  "assets/imagePleases/parks/خطوة جمل.jpeg",
  "assets/imagePleases/parks/شاطي رملة.jpeg",
  "assets/imagePleases/parks/naxos.jpeg",
  "assets/imagePleases/parks/حلم المحيط.jpeg",
  "assets/imagePleases/parks/le pont de l'amitie.jpeg",
  "assets/imagePleases/parks/تشكي تشيز.jpg",
];

List images = [
  "assets/imagePleases/hotels/Assila_Hotel-Exterior.jpeg",
  "assets/imagePleases/hotels/فندق الدار البيضاء.jpeg",
  "assets/imagePleases/hotels/فندق ميراج.jpeg",
  "assets/imagePleases/hotels/فندق كراون بلازا.jpeg",
  "assets/imagePleases/hotels/فندق تاج جدة.jpeg",
  "assets/imagePleases/markets/رد سي مول.jpeg",
  "assets/imagePleases/markets/مجمع العرب.jpeg",
  "assets/imagePleases/markets/عزيز مول.jpeg",
  "assets/imagePleases/markets/روايع المكتبات.jpeg",
  "assets/imagePleases/markets/موفي سينما.jpeg",
  "assets/imagePleases/markets/بيت ورد.jpg",
  "assets/imagePleases/markets/الياسيمن مول.jpeg",
  "assets/imagePleases/markets/هيفاء مول.jpeg",
  "assets/imagePleases/markets/الاندلس مول.jpeg",
  "assets/imagePleases/markets/السلام مول.jpeg",
  "assets/imagePleases/markets/الجامعه بلازا.jpeg",
  "assets/imagePleases/resturant/اغافي.jpeg",
  "assets/imagePleases/resturant/بابايا.jpeg",
  "assets/imagePleases/resturant/اروما.jpeg",
  "assets/imagePleases/resturant/بلو اوشن.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/اكس تريب.jpeg",
  "assets/imagePleases/resturant/ثلث.jpg",
  "assets/imagePleases/resturant/هايد اوت.jpeg",
  "assets/imagePleases/resturant/كافين لاب.jpg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/انجلينا.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/ميز.jpeg",
  "assets/imagePleases/resturant/خيال.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/لوكنشير.jpeg",
  "assets/imagePleases/resturant/تميس.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/ستيتة.jpeg",
  "assets/imagePleases/resturant/نوفل.jpeg",
  "assets/imagePleases/resturant/مكان زمان.jpeg",
  "assets/imagePleases/resturant/سراوند.jpeg",
  "assets/imagePleases/resturant/جامبا.jpeg",
  "assets/imagePleases/resturant/كتشب.jpeg",
  "assets/imagePleases/resturant/القلزم.jpeg",
  "assets/imagePleases/resturant/ازور القهوة المختصة.jpeg",
  "assets/imagePleases/resturant/٩٠ جرام.jpg",
  "assets/imagePleases/resturant/كوينز.jpeg",
  "assets/imagePleases/resturant/كابانا.jpeg",
  "assets/imagePleases/parks/الشلال.jpg",
  "assets/imagePleases/parks/الارض السعيده.jpg",
  "assets/imagePleases/parks/الشلال.jpg",
  "assets/imagePleases/parks/الواجهة .jpeg",
  "assets/imagePleases/parks/موفنبيك.jpeg",
  "assets/imagePleases/parks/ملاهي سماش.jpeg",
  "assets/imagePleases/parks/متحف.jpg",
  "assets/imagePleases/parks/حديقة الفيحا.jpeg",
  "assets/imagePleases/parks/مدينة الملك عبدالله.jpeg",
  "assets/imagePleases/parks/انجليز.jpeg",
  "assets/imagePleases/parks/خطوة جمل.jpeg",
  "assets/imagePleases/parks/شاطي رملة.jpeg",
  "assets/imagePleases/parks/naxos.jpeg",
  "assets/imagePleases/parks/حلم المحيط.jpeg",
  "assets/imagePleases/parks/le pont de l'amitie.jpeg",
  "assets/imagePleases/parks/تشكي تشيز.jpg",
];
